services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag-qdrant
    restart: unless-stopped
    ports:
    - "6333:6333" # REST
    - "6334:6334" # gRPC
    volumes:
    - ./qdrant_storage:/qdrant/storage


# Optional: local LLM via Ollama (if you don't want OpenAI)
# ollama:
# image: ollama/ollama:latest
# container_name: rag-ollama
# restart: unless-stopped
# ports:
# - "11434:11434"
# volumes:
# - ./ollama:/root/.ollama